---
title: "Introduction to the Ocean Health Index Independent Assessment (OHI+)"
output: html_document
---

This portal introduces you to the Ocean Health Index framework and the process for developing an Ocean Health Index Independent Assessment (OHI+). The portal is designed as a course to provide you with all the information required to successfully and autonomously conduct an OHI+ assessment. Therefore, this portal is divided along the four distinct, but interconnected, phases of OHI+:

1. Learn about the Ocean Health Index
2. Plan an Ocean Health Index Independent Assessment
3. Conduct an Ocean Health Index Independent Assessment
4. Communicate and Inform Decision-Making

## Introduction to the Ocean Health Index

The Ocean Health Index is the first integrated assessment framework that scientifically combines key biological, physical, economic, and social elements of the ocean’s health. Overall Index scores are a combination of ten components, or ‘goals’, of ocean health. These scores are calculated using the best available data and indicators at the scale of the assessment. Scores reflect how well coastal regions optimize their potential ocean benefits and services in a sustainable way relative to a reference point (target), on a scale of 0 to 100.
Methods for calculating the Ocean Health Index were developed at a global scale, combining dozens of data sets to produce annual Index scores for coastal nations and territories. Using the same framework, independent assessments allow for exploration of variables influencing ocean health at the smaller scales where policy and management decisions are made. Goal models and targets are created using higher resolution data, indicators, and priorities, which produce scores better reflecting local realities. This enables scientists, managers, policy makers, and the public to better and more holistically understand, track, and communicate the status of local marine ecosystems, and to design strategic management actions to improve overall ocean health.