---
title: "Software for OHI"
output: 
  html_document:
    fig_caption: yes
    keep_md: yes
    number_sections: no
    toc: no
  pdf_document: 
    fig_caption: yes
    toc: no
  md_document:
    variant: markdown_github
---

The Ocean Health Index works primarily with freely available, open-source software. To work the the Toolbox, there are several software programs you will need to download. 

# Required Software

### R

Download [**R from cran.r-project.org**](http://cran.r-project.org/) and follow the install instructions for your computer. 
  
If you already have R installed, check  [**cran.r-project.org**](http://cran.r-project.org/) for updates. There are frequent updates available, and the current version is identified on the website. Compare what is available with what you already have on your computer by typing `sessionInfo()` into your R console (see also: [learning R](http://ohi-science.org/pages/learning_r.html)).
  
  
# Optional Software

### RStudio

We highly recommend working with [**RStudio**](http://www.rstudio.com/products/RStudio/), which is an interface that makes working with R much easier. RStudio also has great compatibility with **GitHub**, which we recommend for conducting regional assessments so you can collaborate with your team easily. RStudio does not get updated as often as R does, but check for updates regularly. 

## Rmarkdown
[Rmarkdown](http://rmarkdown.rstudio.com/) is a powerful way to track progress as you use the Toolbox to reflect the characteristics and priorities in your study region. Here are some [Rmarkdown tips](https://github.com/OHI-Science/ohimanual/blob/master/tutorials/Rmarkdown_tips/Rmarkdown_tips.md#rmarkdown-tips). 




