---
title: 'El Indice de Salud del Océano: Modificar el modelo de una meta<br /> Usando la Caja de Herramientas'
author: "Julia Stewart Lowndes<br /> Cientifico del Proyecto, Ocean Health Index<br /> lowndes@nceas.ucsb.edu"
output: ioslides_presentation
---

## Introducción 

El [**Indice de Salud del Océano (OHI)**](www.oceanhealthindex.org) mide el aprovisionamiento sostenible de diez 'metas' (beneficios y servicios claves) a las personas ahora y en el futuro. A cualquier escala espacial, las evaluaciones OHI usan la mejor información disponible para desarrollar modelos de metas y establecer objetivos, y las puntuaciones de las metas son combinadas para proveer un mejor entendimiento de la salud marino costera.  


**La Caja de Herramientas OHI** es un recurso plataforma a fuente abierta para calcular las puntuaciones OHI a cualquier escala. Aquí, se explorará la Caja de Herramientas. Utilizaremos el repositorio de Belize a nivel global como ejemplo: esto es para propósitos educativos únicamente.  

Nota: esta presentación se hizo con [Rmarkdown](http://rmarkdown.rstudio.com/). Se puede ver producida [en Internet](http://htmlpreview.github.io/?https://github.com/OHI-Science/ohimanual/blob/master/tutorials/github_intro/tutorial_github_intro.html#1) y se puede ver un formato crudo de [GitHub](https://github.com/OHI-Science/ohimanual/blob/master/tutorials/github_intro/tutorial_github_intro.rmd).

## Resumen de la presentación: Mofidicar el modelo de una meta

Demonstraremos un ejemplo de como agregar una nueva variable al modelo de la meta de Oportunidad de Pesca Artesanal (AO) en Belize. 

Aquí, asumimos que su equipo ya ha discutido los factores importantes a considerar en terminos de AO en Belize. El equipo ya ha explorado todos los datos disponibles y ha decidido que la mejor manera de capturar las carateristicas locales es agregando una nueva variable al modelo global de AO.
  

## Resumen de la presentación: Mofidicar el modelo de una meta

El equipo ya ha explorado todos los datos disponibles y ha decidido que la mejor manera de capturar las carateristicas locales es agregando una nueva variable al modelo global de AO.

Pasos: 

1. Revise el modelo global del AO
2. Prepare la capa de datos y guardarla en la carpeta `layers`
3. Registre la capa de datos en el archivo `layers.csv`
4. Actualice el modelo de la meta en `functions.r`
5. Revise y posiblemente actualice `goals.csv`
6. Calcule las puntuaciones; vealas con el WebApp de Belize


## Paso 1: Revise el modelo global del AO

Variables del modelo global de AO: necesidad, acceso, y sostenibilidad. 

$$
D_{U} = (1 - P) * (1 - O_{AO})
$$
$$
x_{AO} = (1 - D_{U}) * S_{AO}
$$

<small>$D_{U}$ = unmet demand</small>  
<small>$P$ = need (PPP-adjusted per capita GDP)</small>  
<small>$O_{AO}$ = access to artisanal fishing</small>  
<small>$S_{AO}$ = sustainability of fishing methods</small>   


## Paso 1: Revise el modelo global del AO

Variables del modelo global de AO: necesidad, acceso, y sostenibilidad. 

$$
D_{U} = (1 - P) * (1 - O_{AO})
$$
$$
x_{AO} = (1 - D_{U}) * S_{AO}
$$

La manera como esto se ve en [`functions.r`](https://github.com/OHI-Science/ecu/blob/028ead581c5dade039941b1aa3524220c454e431/subcountry2014/conf/functions.R#L425-L429):  

```
    Du = (1.0 - need) * (1.0 - access)
    statusData = ((1.0 - Du) * Sustainability)
```

## Paso 1: Revise el modelo global del AO

Digamos que ya hay datos sobre la pobreza en Belize, los cuales pueden ser incorporados como parte de 'necesidad' (el modelo global esta basado sobre necesidad y acceso).


## Paso 1: Revise el modelo global del AO

Digamos que ya hay datos sobre la pobreza en Belize, los cuales pueden ser incorporados como parte de 'necesidad' (el modelo global esta basado sobre necesidad y acceso).

Incorporemos una segunda medida de necesidad llamada $P_{pov}$.

$$
D_{U} = (1 - (P + P_{pov}) / 2) * (1 - (O_{AO})
$$
$$
x_{AO} = (1 - D_{U}) * S_{AO}
$$


## Paso 1: Revise el modelo global del AO

Digamos que ya hay datos sobre la pobreza en Belize, los cuales pueden ser incorporados como parte de 'necesidad' (el modelo global esta basado sobre necesidad y acceso).

Incorporemos una segunda medida de necesidad llamada $P_{pov}$.


$$
D_{U} = (1 - (P + P_{pov}) / 2) * (1 - (O_{AO})
$$
$$
x_{AO} = (1 - D_{U}) * S_{AO}
$$

La manera como esto se ve en [`functions.r`](https://github.com/OHI-Science/blz/blob/9cf957f272e784f557eb75a3a9e5bf7b4677d5d5/subcountry2014/conf/functions.R#L407-L461):  

```
    Du = (1.0 - (need + need_pov) / 2 ) * (1.0 - access)
    statusData = ((1.0 - Du) * Sustainability)
```

## Step 2: Prepare & guarde la nueva capa de datos

### ¿Cuál es el formato de sus nuevos datos?

* [Población por distrito](http://en.wikipedia.org/wiki/Districts_of_Belize)
* [Porcentaje de la población por debajo de la pobreza en Belize](http://www.indexmundi.com/belize/population_below_poverty_line.html)

## Step 2: Prepare & guarde la nueva capa de datos

### ¿Cuál es el formato de sus nuevos datos?

* [Población por distrito](http://en.wikipedia.org/wiki/Districts_of_Belize)
* [Porcentaje de la población por debajo de la pobreza en Belize](http://www.indexmundi.com/belize/population_below_poverty_line.html)  
  
  
### ¿Cuál es el formato de las capas de datos existentes?

* **Explore usando la WebApp blz**
    + http://ohi-science.org/blz/layers

* **Explore el repositorio blz**
    + [acceso](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/layers/ao_access_gl2014.csv)
    + [necesidad](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/layers/ao_need_gl2014.csv)


## Step 2: Prepare & guarde la nueva capa de datos

### Trabajando con datos: buenas practicas

* **organise y prepare los datos en un repositorio de Github** 
    + ex: `github/blz/blz-prep` (el nuestro esta almacenado [aquí](https://github.com/OHI-Science/ohimanual/tree/master/tutorials/tbx_modifications/blz-prep))


## Step 2: Prepare & guarde la nueva capa de datos

### Trabajando con datos: buenas practicas

* **organise y prepare los datos en un repositorio de Github** 
    + ex: `github/blz/blz-prep` (el nuestro esta almacenado ** 
    + ex: `github/blz/blz-prep` (el nuestro esta almacenado [aquí](https://github.com/OHI-Science/ohimanual/tree/master/tutorials/tbx_modifications/blz-prep))
* **documente todos los metadatos** 
    + `README.md`s pueden ser leidos GitHub y contienen información sobre los archivos ([ejemplo](https://github.com/OHI-Science/ohimanual/tree/master/tutorials/tbx_modifications/blz-prep/population))
* **crée un nobre a region para la tabla lookup** la cuál se utiliza para otorgar la identificación de cada region en el área de estudio
    + ej: [`rgn_district_lookup.csv`](https://github.com/OHI-Science/ohimanual/blob/master/tutorials/tbx_modifications/blz-prep/rgn_district_lookup.csv)
* **escriba el script de todas las manipulaciones de datos, de modo que puedan ser reproducidas en el futuro** 
    + [`prep_ao_need.r`](https://github.com/OHI-Science/ohimanual/blob/master/tutorials/tbx_modifications/blz-prep/prep_ao_need_pov.R)

## Step 2: Prepare & guarde la nueva capa de datos

Nuestro R script [`prep_ao_need_pov.r`](https://github.com/OHI-Science/ohimanual/blob/master/tutorials/tbx_modifications/blz-prep/prep_ao_need_pov.R) prepara la capa de datos llamada [`ao_need_pov.csv`](https://github.com/OHI-Science/ohimanual/blob/master/tutorials/tbx_modifications/blz-prep/ao_need_pov_blz2014.csv) con estos pasos:

* Arreglar (Setup)
* Accesar y organización de los datos originales
* Calcular del porcentage de pobreza por distrito
* Agregar los códigos de identificación de las regiones
* Guarde la capa de datos final

## Paso 3: Registre la capa de datos en el archivo `layers.csv`

Como hemos creado una nueva variable, tendremos que agregar una nueva linea a [`layers.csv`](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/layers.csv), con información de las siguientes columnas:

 + **targets:** *AO*
 + **layer:** `ao_need_pov`
 + **name:** el nombre de la capa sera visualizado en su WebApp.
 + **description:** la descripción sera visualizada en su WebApp.
 + **fld_value:** porcentaje
 + **units:** porcentaje
 + **filename:** `ao_need_pov_blz2014.csv`
 + **fld_id_num:** *rgn_id*

## Paso 4: Actualice el modelo en `functions.r`

Actualice el modelo en [`functions.r`](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/conf/functions.R), (y algunas modificaciones a la capa de datos):

```
    Du = (1.0 - (need + need_pov)/2 ) * (1.0 - access)
    statusData = ((1.0 - Du) * Sustainability)
```


## Pasp 5: Revise `goals.csv`

Revise [`goals.csv`](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/conf/goals.csv) si hay algo que necesita ser modificado (particularmente en la columna *preindex_function*)

## Paso 6: Calcule las puntuaciones; visualizarlos con la WebApp

Despues que haga los cambios, puede calcular y visualizar las puntuaciones en diferentes maneras:

1. En RStudio, use el comando [`calculate_scores.r`](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/calculate_scores.R) y visualise las puntuaciones con el comando [`launch_app_code.r`](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/launch_app_code.R)
2. En RStudio, ese el comando [`calculate_scores.r`](https://github.com/OHI-Science/blz/blob/draft/subcountry2014/calculate_scores.R), sincronise cambios a Github y visualise las puntuaciones con la WebApp
3. Sincronise sus cambios a Github: las puntuaciones seran calculadas por internet y pueden ser visualizadas con la WebApp



