---
title: "Ocean Health Index Hawaii - Lead Scientist"
author: "Erich J Pacheco"
date: "August 18, 2014"
output: 
  html_document:
    fig_caption: yes
    keep_md: yes
    number_sections: no
    toc: yes
  pdf_document: 
    fig_caption: yes
    toc: yes
  md_document:
    variant: markdown_github
---

Position title: Ocean Health Index Hawaii - Lead Scientist

Department/Program/Location: Moore Center for Science and Oceans / Hawaii Fish Trust / Honolulu, HI

Supervisor: Jack Kittinger, Ph.D

# Summary
The lead scientist is in charge of developing and implementing a research plan for conducting an Ocean Health Index Regional Assessment for the Hawaiian archipelago. The scientist will work with various stakeholders to develop a strategic plan, gather and analyze data, conduct the main calculations, and produce a scientific publication and technical report of the findings. The position reports directly to the CI-Hawaii Director.

# Key Responsibilities
* The lead scientist will establish partnerships and work with local stakeholders and experts on various fields to:
    + Outline priorities, and identify study area and regions
    + Determine which goals to measure
    + Gather and process data, create spatial reporting units
    + Establish reference points for each goal, and modify goal models (when appropriate or desired)
    + Use the Ocean Health Index Toolbox Application software to calculate scores
    + Document and publish decisions, results, interpretation of scores
    + Create a technical report and/or a peer-reviewed manuscript
    + Support outreach efforts to help inform decision-making and increase awareness
  
* Elicit feedback from experts
* Facilitate discussions and sessions 

## People and resource management responsibilities
* Supervise temporary spatial analysts and R-programmer consultants (if needed)

# Qualifications
* Doctorate (Ph.D) in marine biology, oceanography, biology, marine sciences, natural resource management, or related field
* Experience handling large data sets, making decisions, and thinking creatively
* Excellent organizational and prioritization skills
* Proven experience managing complex scientific projects aimed at informing decision-making
* Four years of experience leading scientific research projects
* Strong verbal and written communication skills and ability to communicate with individuals from a variety of disciplines, cultures and backgrounds

## Additional qualifications
* Basic working knowledge of:
    + ArcGIS (or other spatial analysis software)
    + The software program R
    + User-created packages

# Working Conditions
* Work is performed in a typical office environment
* Some travel may be required within Hawaii to meet with partners and stakeholders