---
title: "Calculate regional assessment scores"
output: 
  html_document:
    fig_caption: yes
    keep_md: yes
    number_sections: no
    toc: no
  pdf_document: 
    fig_caption: yes
    toc: no
  md_document:
    variant: markdown_github
---

\*\* **Note: this page is under development**

It is at this point that it is possible to incorporate all of the decisions your team has made into the OHI framework:

* Goals:
    + which goals to include? 
    + how will the goals be weighted?
* Spatial scale:
    + what are the regions within the study area?
* Data:  
    + which data layers can be updated?
    + which data layers must be changed to develop new goal models?
* Goal models:
    + develop any goal models with the best available data
    
Understanding how the Toolbox is structured can help identify what must be modified for a regional assessemt, particularly with data and models.      

## Modifying and registering data layers
Become familiar with the layers that are included in the global OHI assessment. Each data layer is saved as a separate *.csv* file in the `layers` folder. 
  
- updated data layers
- new data layers

- update layers.csv

- [update goals.csv]()

- update pressures_matrix.csv

- [update resilience_matrix.csv]()

## Updating goal models
- functions.r

